on:
  pull_request:
    types: [labeled]

jobs:
  create_comment:
    if: ${{ github.event.label.name == "ci-detected-performance-change" }}
    runs-on: ubuntu-latest
    steps:
      - name: Comment current pull request
        uses: alawiii521/current-pr-comment@v1.0
        with:
          comment: "@${{ github.event.pull_request.user.login }} :bell: This Pull Request has been identified as containing one or more changes that have potential performance impacts!\n If you haven't already filled out the template to document the impact of these performance changes, you can find the template and more instructions here https://swift-nav.atlassian.net/wiki/spaces/ENG/pages/2170224786/Template+for+documenting+the+impact+of+performance+changes+to+Starling"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
