on:
  label:
    types: [created]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    name: Create a comment
    steps:
      - name: Comment current pull request
        uses: alawiii521/current-pr-comment@v1.0
        with:
          comment: "Hello Howie!"
          GITHUB_TOKEN: ${{ secrets.HOWIE_GITHUB_TOKEN }}
