on:
  pull_request:
    types: [labeled]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    name: Create a comment
    steps:
      - name: Comment current pull request
        uses: alawiii521/current-pr-comment@v1.0
        with:
          comment: "I've been labelled!"
          GITHUB_TOKEN: ${{ secrets.HOWIE_GITHUB_TOKEN }}
