on:
  pull_request:
    types: [labeled]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    name: Create a comment
    steps:
      - name: Comment current pull request
        uses: alawiii521/current-pr-comment@v1.0
        with:
          comment: "@${{ github.event.pull_request.author }} I've been labelled with '${{ github.event.label.name }}'!"
          GITHUB_TOKEN: ${{ secrets.HOWIE_GITHUB_TOKEN }}
